### PR TITLE
Reduction models

### PR DESCRIPTION
**Pull request by andrewheusser**
This PR extends hypertools to support the following dimensionality reduction / manifold learning models:

+ PCA
+ FastICA
+ IncrementalPCA
+ KernelPCA
+ FactorAnalysis
+ TruncatedSVD
+ SparsePCA
+ MiniBatchSparsePCA
+ DictionaryLearning
+ MiniBatchDictionaryLearning
+ TSNE
+ MDS
+ SpectralEmbedding
+ LocallyLinearEmbedding
+ Isomap

The default is PCA, but can be changed to any of the above like so:

```
hyp.plot(data, model='TSNE')
#or
reduced_data = hyp.tools.reduce(data, model='TSNE')
```

Additionally, you can specify model parameters via the `model_params` arg:

```
model_params = {'perplexity' : 40}
hyp.plot(data, model='TSNE', model_params=model_params)
```

### CODE REVIEW

**Comment by jeremymanning** [comment]
This looks awesome!  Assuming the build passes, did you still want me to review it, or is it good to pull into master?

**Comment by andrewheusser** [comment]
i think its good to go. the question is: 0.2.2 or 0.3.0? - its a pretty major enhancement so i would vote for 0.3.0

**Comment by jeremymanning** [comment]
I'm good with 0.3.0!

**Comment by jeremymanning** [comment]
What do you think about defaulting to IPCA instead of PCA?  Tom observed that IPCA gives more consistent results.  Plus, it scales better to big datasets.

**Comment by andrewheusser** [comment]
ipca sounds good to me. we just want to make that clear release notes since its a change in the default behavior. ill switch it now

**Comment by jeremymanning** [comment]
:+1: sounds great.

**Pull request merged**
