### PR TITLE
BIG refactor

### PR DESCRIPTION
**Pull request by andrewheusser**
This was a big refactor, with some new features and also some style changes.  Changes include:

- The way we handle args. Now, all keywords are handled explicitly, instead of unpacking them using the `**kwargs` syntax.  This makes the code much cleaner, and easier to parse arguments.

- The organization of the plotting code. I eliminated the separate static and animate code bases, bc there was a lot of redundant code and handling args was a mess.  its now organized into a plot function, which is the main plotting function that also handles data manipulation prior to plotting, and a draw function, which handles all static and animated drawing.

- Plot styling.  All styles are now consistent, the static plots are now the same as the animated plots.  Also, all lines/points are thinner.

- New keyword arguments to the plot function:
-`fmt` in 0.1.0, format strings were handled as arguments, but now they are passed as a kwarg. since the `fmt` kwarg is the first param after the data, the API in 0.1 and 0.2 is the same, except in 0.1 format strings could be passed in any position, and now they must be passed immediately after the data.
-`title` can be passed to add a title to the plot
-`elev` can be passed to change the elevation of the plot.  useful for static plots in jupyter notebooks
-`azim` can be passed to change the azimuth of a plot. useful for static plots in jupyter notebooks
-`precog` is an animation only feature which plots a low-opacity trace ahead of the data (similar to `chemtrails` but in the opposite direction.
-`bullettime` (animation only) is the same as the combinations of `precog` and `chemtrails`
-`animate='spin'` will create a "static" plot (i.e. all the data is plotted at once) that rotates
-`return_data` has been eliminated.  the data is now always returned by default

Bugs fixed:

- if the rank is of the input matrix is smaller than the number of dimensions requested, the reduce function will now pad the reduced data matrix with `ndims-rank` columns of zeros.

### CODE REVIEW

**Comment by andrewheusser** [comment]
@jeremymanning let me know when you've had a chance to take a peek at the plot [function](https://github.com/ContextLab/hypertools/blob/args-refactor/hypertools/plot/plot.py) and ill merge this into master

**Comment by jeremymanning** [comment]
This looks *fantastic*!  Some suggestions:

_plot.py_:
 - if both color and colors are specified, output a warning that “color” will be ignored in favor of colors
 - same with linestyle(s), marker(s)
 - what happens if fmt indicates a color/linestyle/marker?  which is used preferentially?  (e.g. ‘ro-‘ specifies red, ‘o’ markers, and ‘-‘ linestyle all at the same time).
   - i don’t think the fmt parsing is quite right— e.g. you really want to know if any of [‘-‘, '--', '-.', ':'] are _substrings_ of any of the format strings (for any of the data matrices), not if they’re an exact match.
   - i think we should output a warning if an argument value is ignored or overwritten— so if fmt includes a color and color(s) are specified, we should output a warning that color will be ignored.  (same with linestyle(s) and marker(s))
 - add feature request (issue) to support explore mode for 2d plots

_draw.py_:
 - does plot_square take the scale into account?  it doesn’t look like it…also, shouldn’t the height/width be 2.1 as written?  it looks like it’d be slightly off center as you’ve written it (i.e. the lower left is at (-1.05, -1.05), so we want the upper right to be at (1.05, 1.05), not (1, 1).  but in any case, i think we want the lower left to be at scale*[-1, -1] and the height and width to be 2*scale.
 - as written, bullettime (or precog + chemtrails) plots the data in the current window twice.  i think a more efficient implementation would be an if statement that says something like:
```
if bullettime:
  if ‘precog’ in kwargs.keys() and not precog:
	<output warning that precog will be ignored because bullettime is specified>
  if ‘chemtrails’ in kwargs.keys() and not chemtrails:
	<output warning that precog will be ignored because bullettime is specified>
  precog = True
  chemtrails = True
```
and then you ignore bullettime from there on.
- future feature request: support different selections of bullettime, precog, and chemtrails for different data matrices (e.g. we could show precog on one, chemtrails on another, etc.).  (we’d need to handle warnings differently if we went this route.)
 - support the following animate options, rather than having a separate ‘style’ keyword:
	- animate=‘parallel’ (same as current implementation)
	- animate=True (same as ‘parallel’ for backwards compatibility)
	- animate=‘serial’ (each group plotted one after the other)
	- animate=‘spin’ (plot everything but spin the camera)
	- animate=False (default; no animation)

**Comment by andrewheusser** [comment]
- [ ] _if both color and colors are specified, output a warning that “color” will be ignored in favor of colors, same with linestyle(s), marker(s)_ 
- [ ] _what happens if fmt indicates a color/linestyle/marker? which is used preferentially? (e.g. ‘ro-‘ specifies red, ‘o’ markers, and ‘-‘ linestyle all at the same time)._ **they are passed to matplotlib as the full format string**
- [ ] _i don’t think the fmt parsing is quite right— e.g. you really want to know if any of [‘-‘, '--', '-.', ':'] are substrings of any of the format strings (for any of the data matrices), not if they’re an exact match._ **this is fixed now**
- [ ] _i think we should output a warning if an argument value is ignored or overwritten— so if fmt includes a color and color(s) are specified, we should output a warning that color will be ignored. (same with linestyle(s) and marker(s))_ **added this**
- [ ] _add feature request (issue) to support explore mode for 2d plots_ **added this to the issues**
- [ ] _does plot_square take the scale into account? it doesn’t look like it…also, shouldn’t the height/width be 2.1 as written? it looks like it’d be slightly off center as you’ve written it (i.e. the lower left is at (-1.05, -1.05), so we want the upper right to be at (1.05, 1.05), not (1, 1). but in any case, i think we want the lower left to be at scale*[-1, -1] and the height and width to be 2*scale._ **the reason for this is that the data is scaled to be between -1 and 1, so points right at 1 were being plotted right on top of the border. I added a scale param to the plot_cube function**
- [ ] _as written, bullettime (or precog + chemtrails) plots the data in the current window twice._ **the issue is that `set_data` overwrites if used one after another.  you have to specify the whole dataset to plot in one go.** I could slice the data and concatenate the precog and chemtrails with filler values for the line+tail, but it seems like more work then it is worth. the way its set up currently, `bullettime` plots the full low-opacity data and then the line+tail on top of it.  im going to leave this as it is for now, but will open an issue if you think its worthwhile.
- [ ] _future feature request: support different selections of bullettime, precog, and chemtrails for different data matrices (e.g. we could show precog on one, chemtrails on another, etc.). (we’d need to handle warnings differently if we went this route.)_ **added this issue**
- [ ] _support the following animate options, rather than having a separate ‘style’ keyword_ **if im understanding correctly, this is how i have it set up currently.

**Comment by andrewheusser** [comment]
@jeremymanning i addressed each of your bullets above, and i think we should be good to merge.  when you get a chance, can you take a look, and i'll merge and release 0.2.0 on pip? we should probably do this before tomorrow so we are all up to date for the sprint!

**Comment by jeremymanning** [comment]
this looks great-- merging!

**Pull request merged**
