### PR TITLE
bug fix for passing dict of options to reduce

### LINKED ISSUE #216: replace `as_matrix()` with `.values` in `format_data`
The new version of pandas throws the following warning during calls to `format_data`:
```
/opt/conda/lib/python3.6/site-packages/hypertools/tools/df2mat.py:38: FutureWarning: Method .as_matrix will be removed in a future version. Use .values instead.
  plot_data = df_num.as_matrix()
```
We should use `df_num.values` rather than `df_num.as_matrix()`

### LINKED ISSUE #226: passing ndims to hypertools.reduce erases all other model params
Setting model-specific params is essentially impossible.

If you pass `hypertools.reduce` a dictionary of model params along with a model in the `reduce` argument, and also pass `ndims`, all options except for the chosen model are erased.  

If you try to circumvent this by passing `n_components` to the params dict and not touching the `ndims` argument, line 122 in `hypertools.reduce` causes the function to just return the original data.

https://github.com/ContextLab/hypertools/blob/b76c7ac8061998b560e969ff8e4f4c915088e7a0/hypertools/tools/reduce.py#L127-L152

### PR DESCRIPTION
**Pull request by paxtonfitzpatrick**
this PR fixes #216 and fixes #226. 

changes to `reduce.py`:
- fix issue with custom params dict being overwritten
- as a result, added a new warning for multiple values passed via `ndims` and `n_components`
- moved some fail conditions earlier in the code
- added step to check whether or not model is a supported option & a custom error message if it's not
- added (limited, low-risk) option to pass custom reducer models, both with & without a custom param dict
- added new related error condition (if custom model doesn't support minimum necessary methods)
- minor code cleanup

other changes:
- updated depreciated `pandas.DataFrame` method in `df2mat.py`

### CODE REVIEW

**Comment by paxtonfitzpatrick** [comment]
btw, Travis seems to be failing due to [this issue](https://benlimmer.com/2019/01/14/travis-ci-xvfb/) rather than problem in code

**Comment by paxtonfitzpatrick** [comment]
@jeremymanning This is ready to merge in!  The README already contains instructions for addressing the deepdish/hdf5/pytables issue I was encountering with the python 3.5 build, so that's set.  As for dropping support for 2.7, it's possible to set which version is installed based on python distro version in the configuration for pypi.  However, I'm not sure that's worth it given that we're ~2 weeks from 2.7's EOL and pypi is phasing out support for it anyway.

**Comment by paxtonfitzpatrick** [comment]
agh, hang on, gotta update some files for the new release version first

**Comment by paxtonfitzpatrick** [comment]
added a unit test for the bug fix.  
- The test's format breaks from the simple two-line format of the others in `test_reduce.py`, but this is somewhat necessary to ensure the test operates properly.   
- Also had to run test on a different array from the rest of the `reduce` tests, since the default array is too small and raises a `ValueError` for UMAP.

**Comment by jeremymanning** [comment]
this will become release 0.6.0...

**Comment by jeremymanning** [comment]
removes support for python 2.x and 3.5

**Pull request merged**
